import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavbarContainer from "@/components/nav/NavbarContainer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <NavbarContainer />
        <main className="sm:px-16 px-8 sm:py-24 py-12">{children}</main>
      </body>
    </html>
  );
}
